### ISSUE TITLE
CG/2013-Nachklausur Aufgabe 5a Mailboxing

### ISSUE THREAD

**Issue by pcworld** [MartinThoma/KIT-Musterloesungen#100]
> Die Anzahl der Schnitttests mit Primitiven kann durch Mailboxing weiter reduziert werden.

Das macht für mich bei BVH keinen Sinn. Bei kD dagegen schon, da ein Primitiv auch in mehreren Zellen vorkommen kann.

**Comment by Dav1dK** [comment]
Sehe ich genauso.

**Comment by MartinThoma** [comment]
@pcworld @Dav1dK : Dann macht einen PR. In der commit message Schreibt ihr dann `fixes #100` - damit wird eine Referenz geschaffen und dieses Issue dann automatisch geschlossen
