### ISSUE TITLE
CG/2013-Nachklausur Aufgabe 9a

### ISSUE THREAD

**Issue by ByteHamster** [MartinThoma/KIT-Musterloesungen#113]
normal = transpose(inverse(M)) * normal;

sollte glaube ich heißen:

    normWorld = transpose(inverse(M)) * normal;

**Comment by danstooamerican** [comment]
Die Ausgabe ist ein `vec3` und die Normale sollte noch normalisiert werden.

```glsl
normWorld = normalize((transpose(inverse(M)) * normal).xyz);
```
