### ISSUE TITLE
CG/2013-Nachklausur Aufgabe 7c

### ISSUE THREAD

**Issue by danstooamerican** [MartinThoma/KIT-Musterloesungen#116]
$\lambda_3^\Delta = \frac{1}{3} \leadsto \lambda_3^\Delta = \frac{1}{6}$

$\lambda_1^\Delta = \frac{1}{3} \leadsto \lambda_1^\Delta = \frac{1}{6}$

$\lambda_4^\Delta = \frac{1}{3} \leadsto \lambda_4^\Delta = \frac{2}{3}$

**Comment by MartinThoma** [comment]
Wenn du einen Pull Request aufmachst übernehme ich es gerne :-)
