### ISSUE TITLE
CG/2012-Nachklausur, A2 Blending a)

### ISSUE THREAD

**Issue by s-bach** [MartinThoma/KIT-Musterloesungen#18]
Farbe von glClear vergessen.

Richtig wäre bei (I.):
1. $1.0$
2. $0.5\cdot0.2+0.5\cdot1.0=0.6$
3. $0.5\cdot0.4+0.5\cdot0.6=0.5$
und bei (II.):
1. $1.0$
2. $0.5\cdot0.4+0.5\cdot1.0=0.7$
3. $0.5\cdot0.2+0.5\cdot0.7=0.45$

**Comment by MartinThoma** [comment]
edit: Never mind, ich habs verstanden.

**Comment by s-bach** [comment]
Ich glaub du hast nur den Initialisierungscode in Aufgabenstellung nicht gesehen: glClearColor(1.0,1.0,1.0,1.0).
