### ISSUE TITLE
CG/2012-Nachklausur, A7 Bezierkurven b)

### ISSUE THREAD

**Issue by s-bach** [MartinThoma/KIT-Musterloesungen#20]
(II.) Ist auch $C^1$, weil nach der Tangentenbedingung die Tangenten der Kurve am Rand mit der Geraden durch die beiden Kontrollpunkte am Ende übereinstimmt.
Die Gerade durch $b_2$ $b_3$ ist gleich der Geraden durch $c_0$ $c_1$. Somit auch die Ableitung stetig $\rightarrow$ $C^1$.

**Comment by MartinThoma** [comment]
Verstehe ich dich richtig, dass du im Prinzip sagst, dass die Äquivalenz auf Folie 38:

[F'(1) = G'(0) \Leftrightarrow b_n - b_{n-1} = c_1 - c0]

falsch ist?

**Comment by s-bach** [comment]
Ja würde ich sagen, basierend auf meinen Numerik Kenntnissen.

**Comment by MartinThoma** [comment]
@s-bach Damit liegst du falsch. Siehe https://github.com/MartinThoma/KIT-Musterloesungen/blob/master/CG/Fragen/c2-bezier-spline/minimal-document.pdf

**Comment by upsj** [comment]
Es handelt sich nicht um einen C1-Übergang, aber um einen G1-Übergang:
Diese Parametrisierung ist nicht C1, aber mit einer affinen Reparametrisierung würde man einen glatten C1-Übergang erhalten.
Man muss hier unterscheiden zwischen der Funktion, die die Kurve beschreibt, und der Kurve als geometrisches Objekt. Die Funktion hat einen Knick bei c_0, die Kurve hat keinen Knick.

**Comment by MartinThoma** [comment]
@upsj Was ist ein G1-Übergang? Hatten wir das in der Vorlesung? 

> Man muss hier unterscheiden zwischen der Funktion, die die Kurve beschreibt, und der Kurve als geometrisches Objekt. Die Funktion hat einen Knick bei c_0, die Kurve hat keinen Knick.

Das musst du genauer erklären. Die Kurve als geometrisches Objekt ist nur ein plot der Funktion. Bis auf vertauschung der Reihenfolge der Punkte ([P_0, P_1, P_2, P_3] oder [P_3, P_2, P_1, P_0]) kann man, gegeben die Kurve, glaube ich sogar die Funktion rekonstruieren. Wenn man also "sortierte" Punkte annimmt, dann gibt es vermutlich eine bijektive Abbildung von allen kubischen Bezier-Kurven auf die Menge aller Kurven von kubischen Bezier-Funktionen (ganz sicher bin ich mir nicht, siehe [Frage auf math.SE](http://math.stackexchange.com/q/1685569/6876))

edit: Ok, vermutlich funktioniert es nur wenn man fordert, dass die Kontrollpunkte nicht alle auf der gleichen linie liegen.

**Comment by upsj** [comment]
Das ist ein Begriff aus den "Kurven in CAD"-Vorlesung bzw. der allgemeinen Theorie zu Spline-Kurven und-Flächen.

Die Kurve als geometrisches Objekt ist die Menge aller Punkte auf des Graphen. Um die Kurve als Funktion interpretieren zu können, teilt man jeder Teilkurve ein Definitionsintervall zu und transformiert das Einheitsintervall [0,1] darauf, damit man die Bernstein-Polynome nutzen kann. Daraus erhält man eine stückweise definierte Funktion [a,b] \to \mathbb{R}^2. Wenn diese C^2 ist, ist die zugehörige Kurve C^1. (Das entspricht gleich großen Definitionsintervallen)
Verkleinert man das letzte Teilintervall auf 1/3, hat man einen C^1-Übergang. (Das entspricht der affinen Reparametrisierung)

Allgemein kann man sich das so vorstellen: Die Kurve beschreibt die Fahrt einer Achterbahn, der Parameter beschreibt die Zeit. Wenn die Strecke keine Knicke hat, ist die Kurve G1. Wenn die Geschwindigkeit keine Sprünge macht, ist die Kurve C1.
