### ISSUE TITLE
CG/2013-Nachklausur, A1 Raytracing a)

### ISSUE THREAD

**Issue by s-bach** [MartinThoma/KIT-Musterloesungen#23]
Ein Transmissionsstrahl der den hellen Körper rechts im Bild verlässt fehlt, so auch ein Schattenstrahl vom Austrittspunkt aus.

**Comment by MartinThoma** [comment]
@s-bach Der Transimissionsstrahl, der den hellen Köper verlässt müsste parallel zum eingehenden Strahl sein, oder?

**Comment by s-bach** [comment]
ja glaub schon
