### ISSUE TITLE
CG/2013-Nachklausur, A3 Transformationen c)

### ISSUE THREAD

**Issue by s-bach** [MartinThoma/KIT-Musterloesungen#24]
Rotationsmatrizenmultiplikation ist nicht kommutativ in $R^3$.
Beispiel:
R_x(\pi) \* R_z(\pi) = [1 0 0;0 0 1;0 -1 0] \* [0 1 0;-1 0 0;0 0 1] = [0 1 0; 0 0 1;1 0 0] \ne [0 0 1;-1 0 0;0 -1 0] = [0 1 0;-1 0 0;0 0 1] \* [1 0 0;0 0 1;0 -1 0] = R_z(\pi) \* R_x(\pi)

**Comment by MartinThoma** [comment]
Sehr cool, vielen Dank dafür :-)

**Comment by s-bach** [comment]
Ups, mein Fehler das war nicht $\pi$ sondern $3/2*\pi$

**Comment by MartinThoma** [comment]
@s-bach Was genau muss ich korrigieren?

**Comment by s-bach** [comment]
Überall \pi durch 3/2\cdot\pi ersetzen.
