### ISSUE TITLE
CG/2014-Nachklausur, 6d

### ISSUE THREAD

**Issue by dudanueben** [MartinThoma/KIT-Musterloesungen#28]
Die angegebene Lösung ist falsch.

Im vergleich zu Foliensatz 4 Folie 38 sind b und (1-b) getauscht.

Somit ist t = t12 \* b + t34 \* (1-b)

**Comment by MartinThoma** [comment]
Jup, stimmt. Danke für den Hinweis, ich habs gerade behoben.
