### ISSUE TITLE
CG/2011-Nachklausur, Aufgabe 5

### ISSUE THREAD

**Issue by chbaumgaertner** [MartinThoma/KIT-Musterloesungen#30]
Hier fehlt der Fall, dass der Strahl innerhalb der Kugel startet:

else if (isec.y < t && isec.y > 0)
{
   t = isec.y;
   pos = eye + t \* dir;
   normal = normailize(pos - spheres[i].xyz);
}

**Comment by MartinThoma** [comment]
Duplicate of #19
