### ISSUE TITLE
CG/2015-Hauptklausur, 5c/3

### ISSUE THREAD

**Issue by Amtrix** [MartinThoma/KIT-Musterloesungen#36]
Skalierung?

**Comment by MartinThoma** [comment]
Danke :-) Ich hatte die Frage anders gelesen, als sie dort steht. Ich dachte an das "unnötig eingeschlossene" Volumen. In der Footnote habe ich meinen Gedanken mal hingeschrieben ... das könnte ja auch mal gefragt werden :-)
