### ISSUE TITLE
CG/2015-Hauptklausur, 5b/3

### ISSUE THREAD

**Issue by Amtrix** [MartinThoma/KIT-Musterloesungen#37]
Das ist eine "Grau-Zone", glaube ich. "Sortierung der Primitive notwendig" -- dies scheint mir die Sortierung nach den Objektmittelpunkten zu umfassen.

**Comment by MartinThoma** [comment]
Ja, eventuell. Deshalb habe ich den Kommentar hingeschrieben. Deshalb finde ich Ankreuz-Aufgaben doof.
