### ISSUE TITLE
CG/2013-Nachklausur, Aufgabe 11 (4)

### ISSUE THREAD

**Issue by pjungeblut** [MartinThoma/KIT-Musterloesungen#48]
Frage 4: Ich denke der Operator ist nicht kommutativ. Würde man die Reihenfolge (also SRC und DST) vertauschen, würde ja zweimal der Alpha-Wert von DST genommen. Dieser kann ja anders sein als der Alpha-Wert von SRC.

Bin mir nicht zu 100% sicher, von daher als Issue und nicht als Pull Request.

**Comment by MartinThoma** [comment]
@pjungeblut Bei welcher Aufgabe bist du? Wenn ich mich gerade nicht verschaue hat die NK 2013, Aufgabe 11 keine (b).

**Comment by pjungeblut** [comment]
@MartinThoma Ups, es geht um die Ankreuzaufgabe 11 (4), die vierte Reihe.

**Comment by MartinThoma** [comment]
Anscheinend wurde das zwischenzeitlich behoben. Danke für den Hinweis :-)
