### ISSUE TITLE
CG/2015-Nachklausur, Aufgabe 5a, einfachere Lösung

### ISSUE THREAD

**Issue by matthiasplappert** [MartinThoma/KIT-Musterloesungen#56]
Berechne einfach: `n = normalize(cross(P3-P1,P2-P1))`

**Comment by StephanGocht** [comment]
Ich stimme zu!

**Comment by matthiasplappert** [comment]
Vermutlich wäre auch `n = normalize(cross(P2-P1,P3-P1))` korrekt, da nicht angegeben ist, ob man Vorder- oder Rückseite der Dreiecke sieht.

**Comment by StephanGocht** [comment]
Da die Konvention ist, das Dreiecke CCW angegeben werden würde ich schon davon ausgehen, das man die Vorderseite sieht.

**Comment by fklemme** [comment]
Ich bin auch gerade über diese Stelle gestolpert. Die vorgeschlagene Vereinfachung sollte auf jeden Fall übernommen werden! Die gegebene Lösung ist unnötig kompliziert.
