### ISSUE TITLE
CG/2015-Nachklausur/2015-Nachklausur Lösung für 3b

### ISSUE THREAD

**Issue by StephanGocht** [MartinThoma/KIT-Musterloesungen#59]
z' = E - C
x' = u \times z'
y' = z' \times x'

x,y,z ergeben sich dann noch aus der normalisierung. (Es ist ja eine Orthonormalbasis gefragt, glaub das heißt gerade orthogonale und normalisierte Basisvektoren.)

**Comment by matthiasplappert** [comment]
Habe ich genau auch so. Das KoSys ist dann gegeben durch die normierten Basisvektoren sowie den Ursprung E.
