### ISSUE TITLE
CG/2015-Nachklausur Aufgabe 1 b

### ISSUE THREAD

**Issue by jpaczia** [MartinThoma/KIT-Musterloesungen#60]
Wie schon in Aufgabe 1c) beschrieben (als u und v bezeichnet) ergeben sich die Achsen durch
z=-(C-E)
x=u \dot z 
y= x \dot z

**Comment by MartinThoma** [comment]
1b in der NK 2015? Hast du da vielleicht eine andere Klausur gemeint? In der NK 2015 gibt es keine 1c...

**Comment by StephanGocht** [comment]
Meinst du vielleicht 3b? Dann ist es ein Duplikat mit #59.
Außerdem musst du kreuzprodukt verwenden. Und y = z \times x sonst ist die Orientierung glaub verkehrt (vgl. https://de.wikipedia.org/wiki/Kreuzprodukt - Rechte Hand Regel): Ist a,b gegen den Uhrzeigersin, dann zeigt das Kreuzprodukt zum betrachter.
