### ISSUE TITLE
CG/2015-Hauptklausur Aufgabe 9

### ISSUE THREAD

**Issue by fklemme** [MartinThoma/KIT-Musterloesungen#63]
Fehler in #58:

Punkt 2 ist definitiv falsch! Zitat Foliensatz 07, Seite 15:

> **Primitive Assembly** setzt aus den Vertices die angeforderten Primitive zusammen und ist **nicht programmierbar**.

(Die anderen Punkte hab ich nicht überprüft, nur bei Punkt 2 ist mir der Fehler gleich aufgefallen.)

**Comment by MartinThoma** [comment]
Oops, sorry. Danke fürs aufpassen :-)

**Comment by fklemme** [comment]
Gerne :)

**Comment by jpaczia** [comment]
Hm :D in Foliensatz 7 Teil 1 steht auf Folie 12 das es programmierbar ist. Zitat "große Teile der Pipeline frei programmierbar (...)
- Geometrieverarbeitung, Primitive Assembly, Fragmentverarbeitung
