### ISSUE TITLE
CG/2014-Hauptklausur 1e 3. Aussage

### ISSUE THREAD

**Issue by StephanGocht** [MartinThoma/KIT-Musterloesungen#9]
Jeder Farbeindruck für den Menschen kann mit drei Grundgrößen beschrieben werden.

Ich bin der meinung die Aussage ist richtig. Vgl. 1.d sagt ja nur das der physikalisch realisierbare RGB-Farbraum nicht ausreicht. Trotzdem ist es ein Dreidimensionale Größe (vgl. Graßmannsche Gesetze Folie 6, 01-..-Teil 2).

Soll ich so Anmerkungen lieber in FB oder hier posten?

**Comment by MartinThoma** [comment]
@steohan Danke :-)

Hm, das ist interessant. Heist das, dass die 3 Grundfarben in den Grßmannschen Gesetzen nicht alle monochromatisch sein dürfen? (Ich frage das mal in der Facebook-Gruppe)

Stelle solche "offensichtlichen" Fehler lieber hier auf GitHub als Issue ein. Da kann es jeder sehen und es ist für mich einfacher zu tracken.

**Comment by StephanGocht** [comment]
Doch, du musst halt nur negative werte erlauben.
