### ISSUE TITLE
CG/2015-Nachklausur Aufgabe 4c 

### ISSUE THREAD

**Issue by bjuergens** [MartinThoma/KIT-Musterloesungen#93]
Bei dem Teil 4 c i wird gefragt "Wie verändert sich das Glanzlicht, wenn e größer wird?". Die Antwort sagt, dass es auch intensiver wird. 

Aber das stimmt nicht. Es wird schärfer, und nicht intensiver. 

Das Skalarprodukt von r_l und v ist zwischen 0 und 1 und daher wird ein höherer Exponent den Wert immer verkleinern.

**Comment by MartinThoma** [comment]
@wotanii Warum hast du es geschlossen?

**Comment by bjuergens** [comment]
habe mein github aufgeräumt und alle alten issues zugemacht, die Mal aufgemacht habe.
